{{- if .Values.global.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
{{- if .Values.global.serviceAccount.annotations }}
{{- toYaml .Values.global.serviceAccount.annotations | nindent 4 }}
{{- end }}
{{- end }}